package cm.deepdream.employee.enums;

public enum EmployeeEventType {
	EMPLOYEE_CREATED, EMPLOYEE_UPDATED, EMPLOYEE_APPOINTED, EMPLOYEE_ADVANCED, CONTRACT_STARTED,
	CONTRACT_UPDATED, CONTRACT_TERMINATED, EMPLOYEE_SUSPENDED, SUSPENSION_TERMINATED
}
